### ISSUE TITLE
Bug 35019 - Can't delete news from the staff interface main page

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Bugiton#15]
### Yhteisön bugi Bugzillassa

[Bug 35019](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35019) - Can't delete news from the staff interface main page

**Comment by hanhisalok** [comment]
Tämä olikin jo Signed Off-tilassa.

**Comment by hanhisalok** [comment]
Testasin tämän vielä itse ja toimi. Mutta en tällä kertaa signoffannut Bugzillaan uudestaan.

**Comment by AnneliO** [comment]
Tämä on "pushed to oldstable". Suljen tiketin.
