### ISSUE TITLE
Bug 34966 - Terminology: Add item form - "Add & duplicate" should be "Add and duplicate

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Bugiton#4]
### Yhteisön bugi Bugzillassa

[Bug 34966](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34966) - Terminology: Add item form - "Add & duplicate" should be "Add and duplicate

**Comment by hanhisalok** [comment]
Signed Off 13.10.2023

**Comment by AnneliO** [comment]
Tämä on "Pushed to oldstable", hienoa! :)
