### ISSUE TITLE
Bug 34910 - Do not allow checkout for anonymous patron

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Bugiton#6]
### Yhteisön bugi Bugzillassa

[Bug 34910](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34910) - Do not allow checkout for anonymous patron

**Comment by pknuuti** [comment]
Tämä on signed-off

**Comment by AnneliO** [comment]
Tämä on "Pushed to oldstable", suljen tiketin.
